In [1]:
import numpy as np
import open3d as o3d
import sys

In [2]:
sys.path.append('/mnt/hdd/thuonglc/mocban/woodblock-gt-depth-gen/')

In [3]:
from model_transform_utils import read_stl_file

In [4]:
stl_path = "/mnt/hdd/thuonglc/mocban/woodblock-gt-depth-gen/notebooks/woodblock_border/border_02801_mk30.stl"

In [5]:
border_tri_mesh = read_stl_file(stl_path)

In [6]:
np_tri_mesh = np.asarray(border_tri_mesh.triangles)

In [7]:
np_tri_mesh

array([[0, 1, 2],
       [3, 4, 5]], dtype=int32)

In [8]:
np_3d_points = np.asarray(border_tri_mesh.vertices)

In [9]:
np_3d_points

array([[-171.01301575,  -95.978508  ,   49.01215363],
       [-171.04722595,  -95.97154999,   49.00706863],
       [-171.02001953,  -95.934021  ,   48.97493362],
       [ 167.85794067,  -99.68791199,   34.80282211],
       [ 167.93022156,  -99.68238068,   34.80491638],
       [ 167.9654541 ,  -99.70336151,   34.82095718]])

In [10]:
border_points = []
for i in range(np_tri_mesh.shape[0]):
    mean_point = np.mean(np_3d_points[np_tri_mesh[i], : ], axis=0).tolist()[:2]
    border_points.append(mean_point)

In [11]:
border_points = np.asarray(border_points)

In [12]:
def get_border_points_from_triangle_mesh(border_tri_mesh):
    np_tri_mesh = np.asarray(border_tri_mesh.triangles)
    np_3d_points = np.asarray(border_tri_mesh.vertices)
    border_points = []
    for i in range(np_tri_mesh.shape[0]):
        mean_point = np.mean(np_3d_points[np_tri_mesh[i], : ], axis=0).tolist()[:2]
        border_points.append(mean_point)
    border_points = np.asarray(border_points)
    return border_points

In [13]:
border_tri_mesh = read_stl_file(stl_path)
border_points = get_border_points_from_triangle_mesh(border_tri_mesh)

In [14]:
border_points

array([[-171.02675374,  -95.96135966],
       [ 167.91787211,  -99.69121806]])